# Generated by Django 3.2.8 on 2021-10-13 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookHub_app', '0006_alter_booksreview_star'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_app', '0005_userreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='book',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_book', to='bookHub_app.books'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userreview',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
