# Generated by Django 3.2.8 on 2021-10-13 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_auto_20211013_2133'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserReview',
        ),
    ]
