# Generated by Django 3.2.7 on 2021-10-13 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookHub_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='author',
            new_name='uploader',
        ),
        migrations.RemoveField(
            model_name='books',
            name='name',
        ),
        migrations.RemoveField(
            model_name='books',
            name='upload_time',
        ),
        migrations.RemoveField(
            model_name='books',
            name='writer_name',
        ),
        migrations.AddField(
            model_name='books',
            name='author_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='book',
            field=models.FileField(default=1, upload_to='pdf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='book_category',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='book_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='book_rating',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='book_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='pdf/thumbnails'),
        ),
        migrations.AddField(
            model_name='books',
            name='language',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='uploaded_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
