# Generated by Django 3.2.8 on 2021-10-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookHub_app', '0002_auto_20211011_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_category',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
