# Generated by Django 3.2.8 on 2021-10-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookHub_app', '0003_alter_books_book_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
