# Generated by Django 3.2.8 on 2021-10-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookHub_app', '0003_books_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book',
            field=models.FileField(default=1, upload_to='pdf'),
            preserve_default=False,
        ),
    ]
