# Generated by Django 3.2.8 on 2021-10-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookHub_app', '0005_alter_books_book_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksreview',
            name='star',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
