# Generated by Django 3.2.8 on 2021-10-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookHub_app', '0006_auto_20211011_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_thumbnail',
            field=models.ImageField(default=1, upload_to='pdf/thumbnails'),
            preserve_default=False,
        ),
    ]
