# Generated by Django 3.2.7 on 2021-10-14 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookHub_app', '0008_alter_blogs_created_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='img',
            new_name='thumbnail',
        ),
        migrations.AlterField(
            model_name='blogs',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 11, 43, 25, 808528)),
        ),
    ]
