# Generated by Django 3.2.8 on 2021-10-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookHub_app', '0009_auto_20211011_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='pdf/thumbnails'),
        ),
    ]
