# Generated by Django 3.2.8 on 2021-10-14 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookHub_app', '0010_auto_20211014_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='blogs',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 18, 9, 48, 136644)),
        ),
    ]
