# Generated by Django 3.2.8 on 2021-10-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookHub_app', '0010_alter_books_book_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='book_thumbnail',
        ),
        migrations.AlterField(
            model_name='books',
            name='book',
            field=models.FileField(default=1, upload_to='pdf'),
            preserve_default=False,
        ),
    ]
