# Generated by Django 3.2.8 on 2021-10-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookHub_app', '0011_auto_20211011_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book',
            field=models.FileField(blank=True, upload_to='pdf'),
        ),
    ]
