# Generated by Django 3.2.8 on 2021-10-14 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookHub_app', '0012_auto_20211014_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='email',
            field=models.EmailField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogs',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 15, 0, 6, 29, 226226)),
        ),
    ]
