# Generated by Django 3.2.8 on 2021-10-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookHub_app', '0012_alter_books_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='pdf/thumbnails'),
        ),
    ]
