# Generated by Django 3.2.8 on 2021-10-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookHub_app', '0013_books_book_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
