# Generated by Django 3.2.8 on 2021-10-14 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookHub_app', '0013_auto_20211015_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribers',
            name='subscriber',
        ),
        migrations.AlterField(
            model_name='blogs',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 15, 0, 11, 26, 440976)),
        ),
    ]
