# Generated by Django 3.2.8 on 2021-10-16 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookHub_app', '0014_auto_20211015_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUtils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_text', models.TextField()),
                ('about_us_text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='blogs',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 16, 14, 20, 51, 235978)),
        ),
    ]
