# Generated by Django 3.2.8 on 2021-10-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookHub_app', '0017_alter_books_book_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=1, null=True),
        ),
    ]
