# Generated by Django 3.2.8 on 2021-10-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookHub_app', '0021_alter_books_book_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book',
            field=models.FileField(upload_to='pdf'),
        ),
    ]
